const actions = {
  INIT_SOCKET_CONNECTION_MESSAGE: 'INIT_SOCKET_CONNECTION_MESSAGE',
  CLOSE_SOCKET_CONNECTION_MESSAGE: 'CLOSE_SOCKET_CONNECTION_MESSAGE',
  MESSAGE_SUBSCRIBED: 'MESSAGE_SUBSCRIBED',
  MESSAGE_UNSUBSCRIBED: 'MESSAGE_UNSUBSCRIBED',
  MESSAGE_CHANNEL_UPDATE: 'MESSAGE_CHANNEL_UPDATE',
  MESSAGE_CHANNEL_ERROR: 'MESSAGE_CHANNEL_ERROR',
  MESSAGE_OBJECT_CREATED: 'MESSAGE_OBJECT_CREATED',
  MESSAGE_OBJECT_UPDATED: 'MESSAGE_OBJECT_UPDATED',
  MESSAGE_OBJECT_DELETED: 'MESSAGE_OBJECT_DELETED',
  MESSAGE_CLEAR: 'MESSAGE_CLEAR',
  SEND_MESSAGE: 'SEND_MESSAGE',
  FETCH_CHAT_HISTORY: 'FETCH_CHAT_HISTORY',
  FETCH_CHAT_HISTORY_RESULT: 'FETCH_CHAT_HISTORY_RESULT',
  messageType: {
    system: 'system',
    user: 'user',
  },
  initSocketConnection: (obj) => ({
    type: actions.INIT_SOCKET_CONNECTION_MESSAGE,
    payload: obj,
  }),
  closeSocketConnection: () => ({
    type: actions.CLOSE_SOCKET_CONNECTION_MESSAGE,
  }),
  sendMessage: (obj) => ({
    type: actions.SEND_MESSAGE,
    payload: obj,
  }),
  fetchChatHistory: () => ({
    type: actions.FETCH_CHAT_HISTORY,
  }),
  clearMessage: () => ({
    type: actions.MESSAGE_CLEAR,
  }),
};

export default actions;
